spring:
  application:
    name: onboarding-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
topic:
  budget_allocation_created_events:
    name: budget-allocation-created-events-topic
    partitions: 3
    replicas: 3
    sync: 2
  security_check_created_events:
    name: security-check-created-events-topic
    partitions: 3
    replicas: 3
    sync: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0

springdoc:
  api-docs:
    version: OPENAPI_3_0

client:
  feign:
    account-service:
     url: ACCOUNTING-SERVICE
    security-service:
     url: SECURITY-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuitbreakerevents,retry
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


resilience4j:
  circuitbreaker:
    instances:
      accountServiceCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 4
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - by.javaguru.jdmik4.onboarding_service.exception.BudgetAllocationException
          - by.javaguru.jdmik4.onboarding_service.exception.SecurityCheckException
      securityServiceCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 4
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - by.javaguru.jdmik4.onboarding_service.exception.BudgetAllocationException
          - by.javaguru.jdmik4.onboarding_service.exception.SecurityCheckException
    circuit-breaker-aspect-order: 1
  retry:
    retry-aspect-order: 2
    instances:
      accountServiceRetry:
        max-attempts: 2
        wait-duration: 1000
      securityServiceRetry:
        max-attempts: 2
        wait-duration: 1000






